version: "2"
services:
  web:
    image: node
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c 'npm install && npm start'
    ports:
      - "3000:3000"
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.0.13
    ports:
      - "9000:8080"
    environment:
      - API_URL=http://localhost:3000/petstore.yaml
